Updated HeadScript to allow for proper html5 syntax creation
zf1s/zf1 pull request #103
Opened 2021-09-10 05:15 UTC by glensc

Carry https://github.com/Shardj/zf1-future/pull/107

cc @Nazin

2021-09-10 09:54 UTC, falkenhawk commented
Nice! could we have a test perhaps 😅

2022-10-04 10:11 UTC, falkenhawk requested changes
To get this merged, a test covering the change must be added, possibly to `tests/Zend/View/Helper/HeadScriptTest.php` 🙏

2024-01-23 23:55 UTC, glensc commented
@falkenhawk I don't think I will be working on this. you can close if you don't plan to take over.

2024-02-25 13:44 UTC, falkenhawk approved these changes

2024-02-25 13:47 UTC, merged