Add AllowDynamicProperties Attribute to classes
zf1s/zf1 pull request #145
Opened 2022-11-15 19:20 UTC by glensc

_Carry https://github.com/Shardj/zf1-future/pull/278_

This is to fix the issue:
> `Deprecated: Creation of dynamic property {x} is deprecated`

2022-11-18 10:07 UTC, falkenhawk commented
Thank you for setting this PR! This is going to greatly reduce the amount of deprecation warnings in 8.2. We will tackle this after #141 is finalized, hopefully within next two weeks.

2022-11-28 17:15 UTC, falkenhawk requested changes
On second thought I'd prefer adding missing props, instead of taking a shortcut with adding only class attributes, as this would be a temporary workaround which would throw fatal errors in future php versions.

I took the approach with adding missing attributes in https://github.com/ovos/doctrine1/pull/12 and I've found a few inconsistencies along the way, so I consider those deprecation warnings as one of the most useful ones.

2022-11-28 18:24 UTC, hungtrinh commented
I also want to add the missing props that's why I created https://github.com/Shardj/zf1-future/pull/291 to fix my mess

2022-12-12 10:32 UTC, glensc commented
Needs to include https://github.com/Shardj/zf1-future/pull/291 as well, back to Draft

2023-05-11 16:45 UTC, glensc commented
This is incomplete. should start over porting from z1-future

2023-05-11 16:45 UTC, closed without merging